image:
  repository: 804054839611.dkr.ecr.eu-central-1.amazonaws.com/ecr-repo-18062025214500
  tag: latest
  pullPolicy: IfNotPresent
#  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000
ingress:
  enabled: false
